#!/bin/bash

raw=0
kb=0
byte=0
frequency=1

while getopts ":rkbf:i:" opt; do
  case $opt in
    r)
      raw=1
      ;;
    k)
      kb=1
      ;;
    b)
      byte=1
      ;;
    i)
      IF=$OPTARG
      ;;
    f)
      frequency=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$IF" ]; then
  echo "$0: prints the tx/rx speed/bytes at given network interface in b/s"
  echo "    usage: $0 [-rkb] -i network-interface"
  echo "    e.g. $0 -i eth0"
  echo "    -k sets the unit to kbyte(/s)"
  echo "    -b outputs the total (k)byte; without the output is (k)byte/s"
  echo "    -r outputs in raw format: TIMESTAMP tx rx"
  exit 1
fi

R2=`cat /sys/class/net/$IF/statistics/rx_bytes`
T2=`cat /sys/class/net/$IF/statistics/tx_bytes`
TIMESTAMP=`date +%s.%N`

while true
do
  R1=$R2
  T1=$T2
  OLDTIMESTAMP=$TIMESTAMP
  sleep $frequency
  R2=`cat /sys/class/net/$IF/statistics/rx_bytes`
  T2=`cat /sys/class/net/$IF/statistics/tx_bytes`
  TIMESTAMP=`date +%s.%N`
  DELTAT=`expr $T2 - $T1`
  DELTAR=`expr $R2 - $R1`
  DELTATIME=`echo "scale=8; $TIMESTAMP - $OLDTIMESTAMP" | bc`
  if [ "$byte" -eq 1 ]; then
    if [ "$kb" -eq 1 ]; then
      TSPEED=`expr $DELTAT / 1024`
      RSPEED=`expr $DELTAR / 1024`
      UNIT='kbyte'
    else
      TSPEED=$DELTAT
      RSPEED=$DELTAR
      UNIT='byte'
    fi
  else
    if [ "$kb" -eq 1 ]; then
      TSPEED=`echo "scale=0; $DELTAT / 1024 / $DELTATIME" | bc`
      RSPEED=`echo "scale=0; $DELTAR / 1024 / $DELTATIME" | bc`
      UNIT='kb/s'
    else
      TSPEED=`echo "scale=0; $DELTAT / $DELTATIME" | bc`
      RSPEED=`echo "scale=0; $DELTAR / $DELTATIME" | bc`
      UNIT='b/s'
    fi
  fi
  if [ "$raw" -eq 1 ]; then
    echo -e "$TIMESTAMP $TSPEED $RSPEED"
  else
    echo -e "[$TIMESTAMP]\ttx $IF: $TSPEED $UNIT   \trx $IF: $RSPEED $UNIT"
  fi
done

