#!/bin/bash

raw=0

while getopts ":ri:" opt; do
  case $opt in
    r)
      raw=1
      ;;
    i)
      IF=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$IF" ]; then
        echo $0: prints the tx/rx speed at given network interface in b/s
        echo usage: $0 [-r] -i network-interface
        echo e.g. $0 -i eth0
        echo -r outputs in raw format: timestamp tx rx
        exit 1
fi

while true
do
        R1=`cat /sys/class/net/$IF/statistics/rx_bytes`
        T1=`cat /sys/class/net/$IF/statistics/tx_bytes`
        sleep 1
        R2=`cat /sys/class/net/$IF/statistics/rx_bytes`
        T2=`cat /sys/class/net/$IF/statistics/tx_bytes`
        TBPS=`expr $T2 - $T1`
        RBPS=`expr $R2 - $R1`
        TKBPS=`expr $TBPS / 1024`
        RKBPS=`expr $RBPS / 1024`
        timestamp=`date +%s.%N`
		if [ "$raw" -eq 1 ]; then
          echo -e "$timestamp $TBPS $RBPS"
        else
          echo -e "[$timestamp]\ttx $IF: $TBPS b/s   \trx $IF: $RBPS b/s"
        fi
done

